// <auto-generated />
namespace MVCCodeFirstEFCrud.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class rename_col_custname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rename_col_custname));
        
        string IMigrationMetadata.Id
        {
            get { return "202302271030060_rename_col_custname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
